# Generated by Django 4.2 on 2024-02-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_plantedtree_account_plantedtree_tree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantedtree',
            name='age',
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='latitude_location',
            field=models.DecimalField(decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='plantedtree',
            name='longitude_location',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
